#  Data Scaling
Data scaling is a pre-processing step that transforms the values of numeric variables to have desirable properties for analysis or modeling. 

There are different methods of data scaling, such as normalization and standardization. 

Data scaling can improve the stability and performance of some machine learning algorithms, especially deep learning neural networks.

#### StandardScaler (Standardization)

This is the most famous process, in which the minus-average value (meo) is subdivided by the standard deviation (sigma).

In [3]:
#Import Libraries
from sklearn.preprocessing import StandardScaler
#----------------------------------------------------

#Standard Scaler for Data
X = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler(copy=True, with_mean=True, with_std=True)
new_X = scaler.fit_transform(X)


#showing dataa
print('X : ' , X[:10])
print('\nnew_X \n' , new_X[:10])

X :  [[0, 0], [0, 0], [1, 1], [1, 1]]

new_X 
 [[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [4]:
#Import Libraries
from sklearn.preprocessing import StandardScaler
#----------------------------------------------------

#Standard Scaler for Data
X = [[230, 1085], [1301, 25650], [1351, 11], [10, 12]]
scaler = StandardScaler(copy=True, with_mean=True, with_std=True)
new_X = scaler.fit_transform(X)


#showing dataa
print('X : ' , X[:10])
print('\nnew_X \n' , new_X[:10])

X :  [[230, 1085], [1301, 25650], [1351, 11], [10, 12]]

new_X 
 [[-0.81051822 -0.51156398]
 [ 0.95026275  1.73066442]
 [ 1.0324654  -0.60959586]
 [-1.17220993 -0.60950458]]


#### MinMaxScaler(Normalization)


In which the value is subtracted minus the average on the range, which is the difference between the largest and the smallest value,

 and the proxy of the numbers is so that it is zero to one.


In [5]:
#Import Libraries
from sklearn.preprocessing import MinMaxScaler
#----------------------------------------------------

#MinMaxScaler for Data

scaler = MinMaxScaler(copy=True, feature_range=(0, 1))
new_X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' , new_X[:10])

X 
 [[230, 1085], [1301, 25650], [1351, 11], [10, 12]]
y 
 [[1.64056674e-01 4.18893093e-02]
 [9.62714392e-01 1.00000000e+00]
 [1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.90030812e-05]]


#### Normalizer
It is intended to eat each row separately in two-dimensional matrices
The Normalizer class supports three different types of normalization:

* L1 normalization: This type of normalization scales each sample so that the sum of the absolute values of all the elements in the sample is equal to 1.

* L2 normalization: This type of normalization scales each sample so that the sum of the squares of all the elements in the sample is equal to 1.

* Max normalization: This type of normalization scales each sample so that the maximum absolute value of all the elements in the sample is equal to 1.

In [7]:
#Import Libraries
from sklearn.preprocessing import Normalizer
#----------------------------------------------------

#Normalizing Data

scaler = Normalizer(copy=True, norm='l1') # you can change the norm to 'l1' or 'max' 
new_X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' , new_X[:10])

X 
 [[230, 1085], [1301, 25650], [1351, 11], [10, 12]]
y 
 [[0.17490494 0.82509506]
 [0.04827279 0.95172721]
 [0.99192364 0.00807636]
 [0.45454545 0.54545455]]


In [8]:
#Import Libraries
from sklearn.preprocessing import Normalizer
#----------------------------------------------------

#Normalizing Data

scaler = Normalizer(copy=True, norm='l2') 
new_X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' , new_X[:10])

X 
 [[230, 1085], [1301, 25650], [1351, 11], [10, 12]]
y 
 [[0.20737348 0.97826185]
 [0.05065613 0.99871615]
 [0.99996685 0.00814185]
 [0.6401844  0.76822128]]


In [9]:
#Import Libraries
from sklearn.preprocessing import Normalizer
#----------------------------------------------------

#Normalizing Data

scaler = Normalizer(copy=True, norm='max')
new_X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' , new_X[:10])

X 
 [[230, 1085], [1301, 25650], [1351, 11], [10, 12]]
y 
 [[0.21198157 1.        ]
 [0.05072125 1.        ]
 [1.         0.00814212]
 [0.83333333 1.        ]]


#### MaxAbsScaler
is a transformer that can be used to scale features by their maximum absolute value.

This means that the maximum absolute value of each feature will be equal to 1.0. It does not shift/center the data,
 
and thus does not destroy any sparsity. This scaler can also be applied to sparse CSR or CSC matrices.

scaled_feature = feature / max_abs_value

where:
* scaled_feature is the scaled feature
* feature is the original feature
* max_abs_value is the maximum absolute value of the feature

In [11]:
#Import Libraries
from sklearn.preprocessing import MaxAbsScaler
#----------------------------------------------------

#MaxAbsScaler Data
X = [[ 1., 10., 2.],
     [ 2., 0., 0.],
     [ 5., 1., -1.]]
scaler = MaxAbsScaler(copy=True)
new_X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' , new_X[:10])

X 
 [[1.0, 10.0, 2.0], [2.0, 0.0, 0.0], [5.0, 1.0, -1.0]]
y 
 [[ 0.2  1.   1. ]
 [ 0.4  0.   0. ]
 [ 1.   0.1 -0.5]]


#### FunctionTransformer 
is a transformer that can be used to apply an arbitrary function to the data. This can be useful for performing custom transformations on the data, 

such as taking the logarithm of the features, or adding a custom offset to each feature.

In [12]:
#Import Libraries
from sklearn.preprocessing import FunctionTransformer
#----------------------------------------------------

#Function Transforming Data
'''
FunctionTransformer(func=None, inverse_func=None, validate= None,
                    accept_sparse=False,pass_y='deprecated', check_inverse=True,
                    kw_args=None,inv_kw_args=None)
'''

scaler = FunctionTransformer(func = lambda x: x**2 , validate = True ) # or func = function1
new_X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10]) 
print('y \n' , new_X[:10])

X 
 [[1.0, 10.0, 2.0], [2.0, 0.0, 0.0], [5.0, 1.0, -1.0]]
y 
 [[  1. 100.   4.]
 [  4.   0.   0.]
 [ 25.   1.   1.]]


In [13]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

X = [[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]

def function1(z):
    return np.sqrt(z)

FT = FunctionTransformer(func = function1)
FT.fit(X)
newdata = FT.transform(X)
newdata


array([[2.        , 1.        , 1.41421356, 1.41421356],
       [1.        , 1.73205081, 3.        , 1.73205081],
       [2.23606798, 2.64575131, 2.23606798, 1.        ]])

#### Binarizer
 it converts continuous data into binary data. This can be useful for machine learning algorithms that are sensitive to noise, such as decision trees.

The Binarizer class takes a threshold as its argument.

The threshold is the value that determines whether a feature will be converted to 0 or 1.
 
Features that are less than or equal to the threshold will be converted to 0, and features that are greater than the threshold will be converted to 1.

In [15]:
#Import Libraries
from sklearn.preprocessing import Binarizer
#----------------------------------------------------

#Binarizing Data
X = [[ 1., -1., -2.],[ 2., 0., -1.], [ 0., 1., -1.]]
scaler = Binarizer(threshold = 1.0)
new_X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' ,new_X[:10])

X 
 [[1.0, -1.0, -2.0], [2.0, 0.0, -1.0], [0.0, 1.0, -1.0]]
y 
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]


#### PolynomialFeatures
can be used to create polynomial features from existing features. This can be useful for machine learning algorithms that are not linear in the original features,

 such as support vector machines (SVMs) and decision trees.

The PolynomialFeatures class takes a degree as its argument. The degree is the highest power of the features that will be included in the new polynomial features. 

For example, if the degree is 2, then the new polynomial features will include the original features, as well as the square of each feature.

It's specific to the work of new Fitchers, it's the current Fitchers multiplier product in the polonomic way, so if it were grade 2, for example, and we had already only two columns, or 2 Fitchers, it would give us the order:
1, a, b, a^2, ab, b^2.
Where number 1 in the first to hit it in Theta Zero

In [21]:

import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(3, 2)
print("old X \n",X)

poly = PolynomialFeatures(degree=2 , include_bias = True)
print("\nX1 \n",poly.fit_transform(X))

poly = PolynomialFeatures(interaction_only=True)
# If the interaction_only is selected as a True value, it will only display a values multiplied by b and delete the foundations for the sole values.
print("\nX2 \n",poly.fit_transform(X))


old X 
 [[0 1]
 [2 3]
 [4 5]]

X1 
 [[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]

X2 
 [[ 1.  0.  1.  0.]
 [ 1.  2.  3.  6.]
 [ 1.  4.  5. 20.]]
