In [1]:
import numpy as np


In [3]:
a=np.sin(30)

c=np.sin(30*np.pi/180) # degree
#or
b=np.sin(np.deg2rad(30)) 

d= 1 / np.sin(30*np.pi/180) # cosc


print(a,b,c,d,sep=" ")

-0.9880316240928618 0.49999999999999994 0.49999999999999994 2.0000000000000004


In [5]:
a=np.round(3.6852) # هيقرب للاقرب رقم صحيح
b=np.round(3.6852,1) #هيقرب للاقرب رقم عشري  
c=np.round(3.6852,2)
print(a,b,c,sep=" , ")

4.0 , 3.7 , 3.69


In [7]:
a=np.random.uniform(1,10) 
a
# one random number from1 to 10

4.484132003370901

In [8]:
b=np.random.uniform(1,10,5)
 # five random numbers from1 to 10
b

array([7.4146395 , 7.20214408, 7.94059609, 9.94795255, 8.29590914])

In [9]:
a=np.random.randint(5,size =3)
 # three random integer nambers between 0 and 5
a

array([4, 0, 4])

In [11]:
a=np.random.randint(50)
 # one random integer namber between 0 _ 50
a

33

In [12]:
a=np.random.randint(5,20,size=3) 
# three random integer namber between 5 _ 20
a

array([ 9, 13,  8])

In [19]:
y=[1,2,3,4,5,6,4,7,2,10]
a=np.random.choice(y) 
# random number from list y
a


2

In [21]:
y=[1,2,3,4,5,6,4,7,2,10]
np.random.shuffle(y) 
# بيعمل ترتيب عشوائي لليست
y

[5, 7, 10, 6, 2, 4, 1, 3, 4, 2]

In [22]:
a=np.arange(18) # make list with numbers from 0 to 17 

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [23]:
a=np.arange(2,18) # 2 to 18
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [24]:
a=np.linspace(0,20,5) # هيجيب خمس ارقام بس بين 0 و 20 بس الفرق بينهم متساوي 
a


array([ 0.,  5., 10., 15., 20.])

# Matrix

In [26]:
a=np.array([range(i,i+3)for i  in [2,4,6]])
a
# in[1,2,3,4,5,6]]) creates a NumPy array with 6 rows and 3 columns.
# Each row represents a range of integers, starting with the value of the corresponding 
# index in the list [1, 2, 3, 4, 5, 6] and ending with the value of the index plus 3.
# For example, the first row of the array contains the range of integers from 1 to 4, 
# the second row contains the range of integers from 2 to 5, and so on.



array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [27]:
c=np.random.random((2,2))
 # matrix with random numbers
c

array([[0.35317213, 0.84887096],
       [0.55085369, 0.1287737 ]])

In [28]:
a=np.random.normal(0,1,10)
 # matrix with ten elemnts uisng normal detrubtion
a

array([-0.31939279, -0.16628659,  0.37851641,  0.49104584,  0.10853422,
        1.56271223,  1.9862693 , -0.23316027, -0.7106763 , -0.26165573])

In [29]:
a=np.random.randint(5,20,(3,3)) 
# matrix with intger random numbers between 5 ,20
a

array([[ 8,  7, 11],
       [19, 16,  8],
       [12, 18, 16]])

In [30]:
a=np.random.randint(5,20,(3,3,3)) 
# 3D matrix with random numbers
a

array([[[ 9, 15, 17],
        [19, 12, 17],
        [15,  6,  8]],

       [[ 6,  6,  9],
        [18, 18, 13],
        [17, 14, 17]],

       [[17, 14, 17],
        [13,  7, 12],
        [16,  6, 17]]])

In [36]:
b =np.random.randint(5,10,size=9) 
b = np.reshape(b,(3,3)) # convert list a to matrix 3 * 3
b

array([[9, 6, 9],
       [8, 8, 5],
       [7, 8, 7]])

In [38]:
a=np.arange(18).reshape(3,6) #هيحط الارقام من 0 ل 18 في مصفوفه 3*6
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [39]:
a = np.zeros(8)
a

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
a = np.ones((3,2),int) # = a=np.empty((3,2)) # matrix 3*2 of zeros 
a

array([[1, 1],
       [1, 1],
       [1, 1]])

In [43]:
a = np.eye(2,2) # identity Matrix
a

array([[1., 0.],
       [0., 1.]])

In [44]:
a = np.full((3,5),10) # matrix 3*5 all elemnts = 10
a

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [45]:
a = np.diag(np.array([1,2,3,4]))# هيعمل مصفوفه صفريه وهيحط الارقام دي في القطر الرئيسي
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [47]:
b = np.count_nonzero(a) # number of non zero elemnts in matrix
print(b,'\n')

b = np.count_nonzero(a>7) # number of elemnts that grater than 7 in matrix
print(b,'\n')

b = np.count_nonzero(a>7,axis =1) # هيشتغل بشكل افقي
print(b,'\n')

4 

0 

[0 0 0 0] 



In [55]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b = np.zeros_like(a) 
np.multiply(a,10,out=b) # multiply all elmnts in matrix a by 10 and store res in b
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [56]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b = np.zeros_like(a) 
np.power(a,4,out=b)
b

array([[   1,   16,   81],
       [ 256,  625, 1296],
       [2401, 4096, 6561]])

In [58]:
b = np.add.reduce(a) # hegma3 kol 3naser el matrix 3la ba3d
b

array([12, 15, 18])

In [60]:
b = np.multiply.reduce(a) 
b


array([ 28,  80, 162])

In [62]:
b = np.add.accumulate([1,2,3,4]) # hy3mal gm3 trakome ya3ne kol 3nsor besawe mgmo3 kol ele 2blo 
b

array([ 1,  3,  6, 10])

In [64]:
b = np.multiply.accumulate([1,2,3,4])
b

array([ 1,  2,  6, 24])

In [73]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b = a.size # number of matrix elelmnts 
b = len(a) # number of matrix rows 
b = a.shape # herg3 2b3ad el matrix 
e = a.dtype  # return m type 


In [75]:
c=np.trace(a) # sum of  diagonal elemnts 
c

15

In [76]:
c=np.linalg.det(a) # return the determan of MAtrix
c

0.0

In [78]:
a=np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [80]:
c = a[3,3] # العنصر في الصف الرابع العمود الرابع
b = a[3,:] # fourth row 
b = a[:,3] # fourth column 
d = a[:,1:3] #  كده هيخد كل الصفوف بس من العمود التاني للرابع 
# يعني هيبدئ من التاني وهيقف قبل الرابع 
d

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [81]:
g = a[1:2,:] # من الصف التاني لقبل التالت وكل الاعمده
#يعني الصف التاني بس 
f = a[1:3,2:4]
s = a[2:,3:] # من الصف التالت للاخر ومن العمود الرابع للاخر
s1 = a[:2,:3]
s2 = a[:,-1] # الصفوف كلها والعمود الاخير 
s3 = a[-1,:]
s4=a[::2,::3] # كده بقولو ابدئ من الصف الاول بس امشي خطوتين 
#يعين هيطبع الصف الاول و التالت والخامس وفي الاعمده هيطبع الرابع والسابع 

b = a[:,1:3] # كده هياخد كل الصفوف بس العمود التاني والتالت


In [82]:
b = a[:,1:3].copy() # عشان لو غيرت في المصفوفه الاوله التانيه متتغيرش 
        

In [83]:
a =[0,1,2,3,4,5,6,7,8,9,70]
x1,x2,x3=np.split(a,(3,6)) # كده بقولو قسم الليست لتلات اجزاء من الاول لحد العنصر التالت وحو في متغير 
# ومن الرابع للسابع وحطو في متغير والبااقي في متغير  
x1,x2,x3=np.split(a,(6,3)) # لو الرقم الكبير هو الي جه الاول يبقي هياخد لحد السادس وبعدين هياخد ليستت فاضيه
# وبعدين هياخد من التالت للاخر 
x1

array([0, 1, 2, 3, 4, 5])

In [84]:
b = 2*np.arange(4).reshape(2,2)
b

array([[0, 2],
       [4, 6]])

In [87]:
a= 2*np.arange(4).reshape(2,2)
c =np.vstack((a,b)) # كده هيضم المصفوفيتن معا بعض بشكل رأسي 
print(c,'\n')

c =np.hstack((a,b)) # كده هيضم المصفوفيتن معا بعض بشكل افقي
print(c,'\n')

[[0 2]
 [4 6]
 [0 2]
 [4 6]] 

[[0 2 0 2]
 [4 6 4 6]] 



In [88]:
c = np.concatenate( [ a , b ] , axis = 1 ) # = hstack
print(c,'\n')

c = np.concatenate( [ a , b ] , axis = 0 ) # = Vstack
print(c,'\n')

[[0 2 0 2]
 [4 6 4 6]] 

[[0 2]
 [4 6]
 [0 2]
 [4 6]] 



In [89]:
print( np.argmax(a) ) # كده هيرجعلي مكان اكبر قيمه 

3


In [90]:
C = np.argmin(a)
c

array([[0, 2],
       [4, 6],
       [0, 2],
       [4, 6]])

In [92]:
b = a**2 # squre for all matrix a elemnts 
b

array([[ 0,  4],
       [16, 36]])

In [94]:
c = np.dot(a,b) # multible two matrix 
c

array([[ 32,  72],
       [ 96, 232]])

In [95]:
b = a.sum(axis = 1 ) # sum of each row 
b = a.sum(axis = 0 ) # sum of each column 
b = a.var()
b = a.mean()
b = a.std()

In [96]:
b = np.sort(a,axis = 0 )# sort of each column 
b

array([[0, 2],
       [4, 6]])

In [97]:
b= np.linalg.inv(a) # inverce of a 


In [98]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print(np.ndim(a))

2


# FILES

In [ ]:

fpath =r"G:\BRMAGA\maachine larning\ML\Regression\1.TXT"# partition letter + : \\ + folder name +\\ folder name +\\ filename
dtype1 = np.dtype([("gender","|s1") , ("height","f8")])
# The dtype1 variable is defining the data type of the loaded data.
# In this case, it is a structured data type containing two fields: 'Sex' 
# of type string of length 1 and 'height' of type float.

In [ ]:
a = np.loadtxt(fpath , dtype =dtype1 , skiprows = 2 ,usecols=(1,3) )
#skiprows = 2  de 3shan ytgahel 2wel stren fe el file 
a = np.loadtxt(fpath, dtype=dtype1, skiprows=9, usecols=(1,3)) 
print(a)


In [ ]:
a,b,c = np.loadtxt(r"G:\BRMAGA\maachine larning\ML\Regression\1.TXT", unpack=True,skiprows=3)


In [ ]:
data = np.genfromtxt('D:\\0.txt', skip_header=1,
                  dtype=[('student','u8'),
                         ('gender','|S1'),('black','f8'),
                         ('colour','f8')],delimiter=',',
                         missing_values='X')

# Polynomial

In [104]:
equation = np.polynomial.Polynomial

In [106]:
X= np.array([0,20,40,60,80,100,120,140,160,180])
Y= np.array([10,9,8,7,6,5,4,3,2,1])
# lazem len x = len y
points,state = equation.fit(X, Y, 1, full = True )
print(points)
print(state)


5.5 - 4.5 x
[array([5.62063395e-30]), 2, array([1., 1.]), 2.220446049250313e-15]


In [107]:
a =  np.poly1d((-7))  # 7d motlq 
b =  np.poly1d((-7,2)) # x , 7d motlq
c =  np.poly1d((-7,2,1)) # x^2 , x , rqam 
d =  np.poly1d((-7,2,1,3))
e =  np.poly1d((-7,2,1,3,6))
e

poly1d([-7,  2,  1,  3,  6])

In [109]:
a= np.polyval((7,2),5)  # hy3mal mo3dla we y3wod feha b 5
a

37

In [110]:
a = np.polyder(c) # 2shtqaq el function c 
a

poly1d([-14,   2])

In [111]:
a = np.polyder(c,2)# 2shtqaq el function c marten 
a = np.polyder(c,3)# 2shtqaq el function c tlat mrat  
a

poly1d([0])

In [112]:
a =np.polyint(np.poly1d((1,2,3))) #tkamol
a =np.polyint(np.poly1d((1,2,3)),2) 
a

poly1d([0.08333333, 0.33333333, 1.5       , 0.        , 0.        ])

In [113]:
print(b(0)) # kda hy3od be zero fe mo3dlet b 

2


In [114]:
a =np.roots(np.poly1d((1,2)))
a

array([-2.])

# DATE

In [115]:
x = np.array('2015-07-04', dtype=np.datetime64)
#or 
x = np.datetime64('2015-07-04')
x

numpy.datetime64('2015-07-04')

In [116]:
y = x + np.arange(12)  # hezzod 11 yoam
y

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
      dtype='datetime64[D]')

In [118]:
y = x - np.arange(12) # hetra7 2yam
y

array(['2015-07-04', '2015-07-03', '2015-07-02', '2015-07-01',
       '2015-06-30', '2015-06-29', '2015-06-28', '2015-06-27',
       '2015-06-26', '2015-06-25', '2015-06-24', '2015-06-23'],
      dtype='datetime64[D]')

In [119]:
z = y-x # fr2 el 2yam 

# functions in numpy

In [120]:
c= np.fromfunction(lambda i:i**3,  (10,))
# hy3mel matrix feha 2rkam mn 0 to 10 we hat moka3b kol 3onsor feha 
#lambda 3shan lw 3awez 23mel function fe satr wa7ed  
c

array([  0.,   1.,   8.,  27.,  64., 125., 216., 343., 512., 729.])

In [121]:
def powers(i):
    i = i**2
    return i
 
x = np.fromfunction(powers, (9,), dtype=int)
x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])